#!/bin/bash
#1-store
cd $PROJECT_ROOT
tar -cvJf _sensitive_datas/_sensitive_datas.tar.xz .vscode/launch.json .vscode/settings.json ./launch-* ./*.pem ./*.key .wrangler/state/kv/KV_TOKENS/ crowdin.yml
#2-encrypt
openssl aes-256-cbc -base64 -md sha256 -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz
